version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=next-saas
